### ISSUE TITLE
Get frontend files into backend-develop

### ISSUE THREAD

**Issue by TylerMetz** [TylerMetz/Saucier720#108]
### Description
`develop-backend` has not been caught up with `develop` and to make the PRs look nice we need to do this

### Definition of Done
`develop-backend` has fronted files from Sprint 1

**Comment by TylerMetz** [comment]
@rileycleavenger @samforstot idk if y'all want this but i made an issue for it

**Comment by rileycleavenger** [comment]
Merged them both into the [Connect branch](https://github.com/TylerMetz/Saucier720/tree/Connect)
