### ISSUE TITLE
Push Gorillamux data to non-local server port

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#117]
### Description
see title

**Comment by rileycleavenger** [comment]
https://www.syncfusion.com/succinctly-free-ebooks/go-web-development/serving-and-routing

**Comment by rileycleavenger** [comment]
Not sure if this is possible, pushing to Sprint 3 for now

**Comment by samforstot** [comment]
Not possible, not too much of a concern
