### ISSUE TITLE
Figure out how to include other Packages in our repo

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#119]
### Description
When you push/pull from the repo the other package files don't go with it, we might need to use submodules

**Comment by rileycleavenger** [comment]
attempted to do it with the mux and selenium packages, not sure if it's functioning correctly, reevaluating in Sprint 3

**Comment by TylerMetz** [comment]
https://stackoverflow.com/questions/61305116/go-not-resolving-github-package-imports
this might help? we need to convert them to go modules i think?

**Comment by rileycleavenger** [comment]
We did this with submodules, is functioning correctly now for all included packages
