### ISSUE TITLE
Implement Crud Helper Service in Angular

### ISSUE THREAD

**Issue by TylerMetz** [TylerMetz/Saucier720#229]
### Description
There is currently an Http service that is not being properly utilized. To be able to make Http request easier down the road as we implement more. It would be nice to have this helper service

### Definition of Done
- Http Service can implement
- [ ] Post
- [ ] Put
- [ ] Replace
- [ ] Delete

**Comment by emenello** [comment]
Not required. Already very easy to make http requests and helps understand code without convolution
