### ISSUE TITLE
Backend Reorganization 

### ISSUE THREAD

**Issue by TylerMetz** [TylerMetz/Saucier720#244]
### Description
We need to go through the backend and reorganize so that we can properly establish functions and methods to assist in sending data to the frontend. There are currently methods and files being called in many different styles.
`Example`: the router class has routers being used in many different places

### Definition of Done
Backend is efficiently organized for use

**Comment by rileycleavenger** [comment]
LGTM

**Comment by rileycleavenger** [comment]
Changes made [here](https://github.com/TylerMetz/Saucier720/pull/267)
