### ISSUE TITLE
Information about how each page works

### ISSUE THREAD

**Issue by samforstot** [TylerMetz/Saucier720#347]
### Description
We need to consider how a person who has never seen the page how each thing works. I think it would be a good idea to include a header explaining each tab or Tyler's idea of clicking a question mark and a box with the info appears. 
### Definition of Done
Users can understand how each page works with no issues.

**Comment by rileycleavenger** [comment]
I added these to FAQs on the homepage, so going to close this. We can revisit the idea if we want more detailed info

**Comment by rileycleavenger** [comment]
I added these to FAQs on the homepage, so going to close this. We can revisit the idea if we want more detailed info
