### ISSUE TITLE
Seasoning Section on the Pantry

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#364]
### Description
Seasonings do not match the current quantity display for items in your pantry

### Definition of Done
Efficient way for users to view seasonings they currently own.

**Comment by TylerMetz** [comment]
My idea for this is to show a seasoning shaker that is clickable next to each seasoning. Each time you click the shaker it would the amount inside decrease by 25%, starting at 100 when added, when the shaker is at 0 the user can then have the option to add it to refill or delete it. If they click neither the shaker will sit on the screen empty.

**Comment by rileycleavenger** [comment]
Closing to combine with #365
