### ISSUE TITLE
Use Regex or string manipulation to get rid of &amp that appears with some deal items 

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#377]
### Description
Some deals are read in as "&amp" and need to be fixed

**Comment by samforstot** [comment]
@rileycleavenger Unassigning from myself becomes redundant if moving scraper to python and reorganizing.

**Comment by samforstot** [comment]
Redoing scraper, this issue is no longer needed as it will be fixed with the python transition
