### ISSUE TITLE
Host MealDealz online using Microsoft Azure

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#379]
### Description
As students we get access to MS Azure for free and can use this to host MealDealz and our database. 

## Basic Steps
**1)** Sign up for Azure: If you haven't already, sign up for a student Azure account or activate your student benefits through Azure for Students.
**2)** Create a new Web App: Once you have access to Azure, log in to the Azure Portal (https://portal.azure.com/). Click on "Create a resource" and search for "Web App". Select the appropriate option (e.g., "Web App" or "Web App (Linux)") based on your requirements.
**3)** Configure the Web App: Provide the necessary details for your web app, such as the name, subscription, resource group, and operating system. Choose the appropriate operating system depending on your Golang backend (Windows or Linux). Select the appropriate pricing tier and click on "Review + create" to proceed.
**4)** Create an Azure Database: If your Golang backend requires a database, you can create an Azure Database for PostgreSQL or MySQL. Search for "Azure Database for PostgreSQL" or "Azure Database for MySQL" and create a new instance. Take note of the connection details, such as the server name, username, and password.
**5)** Deploy the backend: To deploy your Golang backend, you have multiple options. One approach is to use Azure App Service with Docker containers. You can containerize your Golang application and deploy it to Azure Container Registry (ACR) or Docker Hub. Then, configure the Azure Web App to use the container image. Alternatively, you can also deploy your Golang application directly to Azure Web App using the built-in deployment options for Go.
**6)** Deploy the frontend: To deploy your Angular frontend, you can use Azure Blob Storage or Azure Static Web Apps. Azure Blob Storage allows you to host static websites easily. Another option is Azure Static Web Apps, which provides a more integrated workflow for deploying and hosting your Angular application. You can use Azure DevOps or GitHub Actions for automatic deployments.
**7)** Connect frontend to backend: Update your Angular frontend code to point to the appropriate API endpoints of your Golang backend. This typically involves configuring the API base URL in your Angular environment files or using environment variables.
**8)** Test and validate: Once both the backend and frontend are deployed, test the web application to ensure it's functioning correctly. Verify that the frontend can communicate with the backend APIs and perform the desired functionality.

**Comment by TylerMetz** [comment]
DATABASE.GO!
