### ISSUE TITLE
Remove all school items 

### ISSUE THREAD

**Issue by samforstot** [TylerMetz/Saucier720#391]
### Description
Get rid of school stuff so that we don't need to think about it. Check each sprint folder and remove them as needed. Pretty sure they will exist in other versions anyway. 

### Definition of Done
No trace of the sprint assignments in the branches

**Comment by samforstot** [comment]
@rileycleavenger fixed it in walmart branch. Will merge soon.

**Comment by rileycleavenger** [comment]
Fixed it in PR #399 and PR #400
