### ISSUE TITLE
Make the Publix scrape function in Python

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#395]
### Description
The Publix scrape function currently runs in Golang, but we could redo it as a Python script using Selenium and BeautifulSoup, and potentially have it running faster and without a data parsing function

**Comment by samforstot** [comment]
Notes: 
- Line that scrapes is in check if
- Stored in foodItem slice
- Compares time, clears data, saves deals 
- exec.command to run python script
- cmd.output
- Parse output 
- Beautiful soup allows you to parse out of html easily 
- String manipulation finds product finds price 
- Opens selenium + url 
- gets page source
- for publix click the load more button

**Comment by samforstot** [comment]
Scrape functions may need to be altered depending on the computer you use. Might need to make some kind of documentation note about paths / exit errors.

**Comment by samforstot** [comment]
Need to fix any special symbols and check if we can switch to webdriver-manager for all scrapes rather than driver path

**Comment by samforstot** [comment]
Special symbols fixed, walmart convert may be a little trickier
