### ISSUE TITLE
Find a way to have each Chromedriver window run asynchronously when scraping Walmart 

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#396]
### Description
Currently the Walmart scraper has to go through the deals pages one page at a time, but if we could run all x number of pages (total page number gotten from the first page) at once, it would scrape way faster. I'm not sure if this would require more processing power than we have, or if it's even possible running multiple instances with Selenium, but it might be worth a try.

**Comment by samforstot** [comment]
PR #435 Solved this issue!
