### ISSUE TITLE
Allow users to add to their shopping list from the Recipes and Deals pages

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#407]
### Description
- Add "+" button to the left of each ingredient in a recipe that adds the item to a user's list with a quantity of "1"
- Add "+" button to the left of each item on the deals page that adds the item to a user's list with a quantity of 1
- "+" button turns dark or grayed out after being selected

### Important Notes
- Can reuse Listen backend function for adding a List item where it gets data from address 8082/api/NewItem, therefore this requires no backend changes at all 
- Just need to make a frontend POST function to the 8082/api/NewItem address for the Deals page and Recipe page that is activated when selecting the "+" button

**Comment by rileycleavenger** [comment]
closing issue #424 because I didn't know I had this open

**Comment by rileycleavenger** [comment]
### Description
- Add "+" button to the left of each ingredient in a recipe that adds the item to a user's list with a quantity of "1"
- Add "+" button to the left of each item on the deals page that adds the item to a user's list with a quantity of 1
- "+" button turns dark or grayed out after being selected

### Important Notes
- Can reuse Listen backend function for adding a List item where it gets data from address 8082/api/NewItem, therefore this requires no backend changes at all 
- Just need to make a frontend POST function to the 8082/api/NewItem address for the Deals page and Recipe page that is activated when selecting the "+" button

**Comment by samforstot** [comment]
Closed with PR#465
