### ISSUE TITLE
Add new pantry item or new list item to pantry/list without requiring a page refresh

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#434]
### Description
Right now when adding a new list or pantry item it refreshes the page and loads it from the backend. To avoid the page refresh we could just put the item in the list/pantry AND post it to backend, that way the page doesn't need refreshing, then when the page is eventually reloaded it'll still populate the new item, but this time from backend. This is a really easy change, just remove the refresh line and replace it with a command to add it to the table.

**Comment by rileycleavenger** [comment]
Also change it so we don't need a refresh when selecting new settings on the recipes page

**Comment by rileycleavenger** [comment]
we figured out the pantry item, just need to do the same for the list

**Comment by samforstot** [comment]
List was easier than pantry item, doing recipes filter now.

**Comment by samforstot** [comment]
closed with #481
