### ISSUE TITLE
Relook at scrapers. 

### ISSUE THREAD

**Issue by samforstot** [TylerMetz/Saucier720#458]
### Description
The walmart deals are only scraping up to a certain point, need to check it out and resolve. 
### Definition of Done
Walmart deals scrape entirely.

**Comment by samforstot** [comment]
Publix aint scraping again, will look later.

**Comment by samforstot** [comment]
Pulix working fine, we need to keep track of when the manager updates so that it doesnt break down .

**Comment by samforstot** [comment]
Walmart does not allow you to scrape, I will check the following brands with selenium to see if it's possible to make up for the loss: 

- [ ] Target
- [ ] Trader Joes
- [ ] Aldi
- [ ] Sam's Club
- [ ] Costco
- [ ] Winn Dixie

**Comment by samforstot** [comment]
Target - "https://www.target.com/c/grocery-deals/-/N-k4uyq"
Aldi - "https://www.aldi.us/en/weekly-specials/our-weekly-ads/"
Sam's Club - "https://www.samsclub.com/b/instantsavings-pantry/7130123"
Costco = "https://www.costco.com/grocery-household.html?keyword=OFF&dept=All&hide-unavailable-items=in-stock&deliveryFacetFlag=true&refine=||item_program_eligibility-ShipIt||item_location_availability-in%2Bstock&sortBy=item_page_views+desc"

**Comment by samforstot** [comment]
I found a different costco link: "https://www.costco.com/grocery-household.html?keyword=OFF&dept=All&sortBy=item_page_views+desc"

At this point both target and aldi scrape, sams club is out as it is related to walmart

**Comment by rileycleavenger** [comment]
Costco works, going to try Kroger tomorrow for the midwest goons

**Comment by samforstot** [comment]
closed with #479
