### ISSUE TITLE
List page not loading fully everytime

### ISSUE THREAD

**Issue by samforstot** [TylerMetz/Saucier720#467]
### Description
For some reason the list page is inconsistent when it loads. I don't know if it is because of our current backend or what but it means that other functions like add to list and validating items won't work consistently from other pages
### Definition of Done
Make sure the list loads consistently every time.

**Comment by rileycleavenger** [comment]
I'm having the same issue on the pantry page rip

**Comment by rileycleavenger** [comment]
Update: I think I fixed it in backend in my current working branch
