### ISSUE TITLE
Update Scrapers to New Selenium

### ISSUE THREAD

**Issue by samforstot** [TylerMetz/Saucier720#492]
Our scrapers need to be udpated with Selenium, no scraping will work if we dont!

**Comment by rileycleavenger** [comment]
See https://github.com/rileycleavenger/GatorPathTracker/issues/2 thread for more details

**Comment by rileycleavenger** [comment]
Updated the Publix scraper, see [this branch](https://github.com/TylerMetz/Saucier720/tree/BUG-492-SeleniumUpgrade)

**Comment by rileycleavenger** [comment]
I hate Kroger.

**Comment by rileycleavenger** [comment]
@samforstot please check out the Target scraper when you get a chance

**Comment by samforstot** [comment]
> @samforstot please check out the Target scraper when you get a chance

I checked it out, was just an issue with the css selector changing. Should try and implement a new solution.
