### ISSUE TITLE
Update Scrapers into Azure

### ISSUE THREAD

**Issue by TylerMetz** [TylerMetz/Saucier720#495]
### Description
Azure can support to automation of our scrapers rather than golang.

Heres a good resource I found https://towardsdatascience.com/how-to-create-a-selenium-web-scraper-in-azure-functions-f156fd074503

### Definition of Done
- [ ] Scraper adds to the deals_data table in an automated schedule

**Comment by rileycleavenger** [comment]
Same As #480
