### ISSUE TITLE
Sprint 2 Goal: Webscrape 

### ISSUE THREAD

**Issue by samforstot** [TylerMetz/Saucier720#70]
### Description
Learn how to and implement webscraping!

**Comment by rileycleavenger** [comment]
I have tried multiple packages to web scrape over the last week with no success, more details can be found here at [THIS](https://github.com/TylerMetz/Saucier720/issues/94) issue. This might become a Sprint 3 goal.

**Comment by rileycleavenger** [comment]
Final Update: I successfully web scraped the Publix website in [THIS](https://github.com/TylerMetz/Saucier720/tree/functioningSelenium) branch!
