### ISSUE TITLE
Create a dashboard

### ISSUE THREAD

**Issue by emenello** [TylerMetz/Saucier720#77]
### Description
Create a dashboard with pantry, cart, deals, and recipes taking you to different pages. Pages can be empty but button UI functions. 
### Definition of Done
4 working buttons that take the user to 4 different pages.

**Comment by TylerMetz** [comment]
https://medium.com/@2muchcoffee/creating-basic-angular-application-in-10-minutes-part-1-8bb6e21b9446

**Comment by TylerMetz** [comment]
https://www.w3schools.com/howto/howto_js_topnav.asp
https://www.npmjs.com/package/angular-cli-ghpages
