### ISSUE TITLE
Create Routing App

### ISSUE THREAD

**Issue by emenello** [TylerMetz/Saucier720#81]
### Description
Create a routing app in angular to link URLs to the right components to make the page navigation easier.
### Definition of Done
When the URLs can be linked to the correct components. URLs will pull up correct pages.

**Comment by TylerMetz** [comment]
https://www.homeandlearn.co.uk/WD/wds5pA.html#:~:text=Linking%20in%20HTML%20code%20is,see%20how%20to%20do%20later.
