### ISSUE TITLE
Create list page

### ISSUE THREAD

**Issue by TylerMetz** [TylerMetz/Saucier720#82]
### Description
Make an html page for the `list` page.

### Definition of Done
Create an html page that has 
[ ] list ingredients added to shopping list (each with quantity and name)
[ ] buttons to adjust quantity and delete
[ ] place to add a new item to list with name and quantity
[ ] "export" button, that has no functions currently

**Comment by rileycleavenger** [comment]
You can probably copy the pantry page html, just change however you please.

**Comment by rileycleavenger** [comment]
Add a "List" tab on the top bar
