### ISSUE TITLE
Sprint 2 Goal: Frontend Backend Communication

### ISSUE THREAD

**Issue by samforstot** [TylerMetz/Saucier720#87]
### Description
Be able to communicate data between both teams

**Comment by emenello** [comment]
https://webkul.com/blog/communicating-with-backend-server-in-angular-js/

**Comment by TylerMetz** [comment]
https://angular.io/api/common/http

**Comment by TylerMetz** [comment]
https://angular.io/guide/http

**Comment by rileycleavenger** [comment]
[Auth0 Part 1 with GO](https://auth0.com/blog/developing-golang-and-angular-apps-part-1-backend-api/)
[Auth0 Part 1 with TS](https://auth0.com/blog/developing-golang-and-angular-apps-part-2-angular-front-end/)

**Comment by rileycleavenger** [comment]
It works now, see [the Connect Branch](https://github.com/TylerMetz/Saucier720/tree/Connect)
