### ISSUE TITLE
Can't use colly to web scrape because it can't activate js scripts

### ISSUE THREAD

**Issue by rileycleavenger** [TylerMetz/Saucier720#94]
### Description
I'm attempting to scrape [the Publix Deals page](https://www.publix.com/savings/weekly-ad/view-all), but can't with colly since the landing page requires you to press a button, something which colly can't do. Therefore, I'm planning on using Selenium, a WebDriver, to open the page in a virtual browser and select the correct buttons. Then from there I'll pass the appropriate link through Colly and scrape each product's data individually.

**Comment by rileycleavenger** [comment]
### Resources
https://pkg.go.dev/github.com/tebeka/selenium
https://github.com/tebeka/selenium

**Comment by rileycleavenger** [comment]
Update: Selenium won't run on Mac, having [THIS](https://github.com/netblue30/firejail/issues/1197#issuecomment-329901282) same issue and it doesn't seem to have a fix! I'm going to try Chromed. My Selenium script remains on [THIS](https://github.com/TylerMetz/Saucier720/tree/SeleniumMain) branch.

**Comment by rileycleavenger** [comment]
Update: I attempted to use PhantomJS to webscrape, as seen on [THIS](https://github.com/TylerMetz/Saucier720/tree/phantomJS) branch. Unfortunately the code it's returning contains placeholder HTML content, which contains the items grid, but not the actual items.

**Comment by rileycleavenger** [comment]
Update: I attempted to scrape the data using DataflowKit API, which also didn't work, but the code can be found at [THIS](https://github.com/TylerMetz/Saucier720/tree/DataflowKitScraping) branch.

**Comment by rileycleavenger** [comment]
Update: I tried using Chromedp and it still isn't working. I can't get the first button to activate on the first page. I'm going to try more later, but was mostly using the [example](https://github.com/chromedp/examples) and [documentation](https://pkg.go.dev/github.com/chromedp/chromedp#pkg-overview) resources. [THIS](https://github.com/TylerMetz/Saucier720/tree/Chromedp) branch is the one with the Chromedp code.

**Comment by rileycleavenger** [comment]
Update: I have it functioning using Selenium! The code for it is in [THIS](https://github.com/TylerMetz/Saucier720/tree/functioningSelenium) branch. I also just got it to display all of the items by pressing the "Load More" button until it can't find it in the HTML.

**Comment by TylerMetz** [comment]
@rileycleavenger if you could make a draft PR so we can look at the files that would be awesome

**Comment by rileycleavenger** [comment]
@TylerMetz Will do!

**Comment by rileycleavenger** [comment]
@TylerMetz [Here](https://github.com/TylerMetz/Saucier720/pull/115) is my PR
