### ISSUE TITLE
Create wireframe for Recipes page

### ISSUE THREAD

**Issue by TylerMetz** [TylerMetz/Saucier720#98]
### Description
Make a wireframe for #84 

### Definition of Done
Clearly shows how and where data will be displayed to user

**Comment by rileycleavenger** [comment]
<img width="1392" alt="Screenshot 2023-04-06 at 1 28 46 PM" src="https://user-images.githubusercontent.com/73538882/230452709-8accee68-fbe7-42dc-b073-3917f6fbbb7d.png">

**Comment by emenello** [comment]
Lmao nice design pathetic
